In [31]:
# 创建表
import pandas as pd

In [32]:
# 创建学生成绩表
data = [['001','张三',85,90,88],
        ['002','李四',78,85,92],
        ['003','王五',90,88,85],
        ['004','赵六',60,70,65],
        ['005','孙七',80,82,78]]

df_score = pd.DataFrame(data,columns=['学号','姓名','数学','英语','计算机'])
df_score

    学号  姓名  数学  英语  计算机
0  001  张三  85  90   88
1  002  李四  78  85   92
2  003  王五  90  88   85
3  004  赵六  60  70   65
4  005  孙七  80  82   78

In [33]:
# 创建销售表
data_sale = {
    '日期':['2024-01-01','2024-01-01','2024-01-02','2024-01-02','2024-01-03'],
    '地区':['北京','上海','北京','广州','上海'],
    '产品名称':['产品A','产品B','产品A','产品C','产品B'],
    '销售数量':[10,15,12,8,10],
    '销售金额':[200,300,240,160,200]
}
df_sale = pd.DataFrame(data_sale)
df_sale

           日期  地区 产品名称  销售数量  销售金额
0  2024-01-01  北京  产品A    10   200
1  2024-01-01  上海  产品B    15   300
2  2024-01-02  北京  产品A    12   240
3  2024-01-02  广州  产品C     8   160
4  2024-01-03  上海  产品B    10   200

In [34]:
with pd.ExcelWriter("数据.xlsx", engine='openpyxl') as writer:
    df_sale.to_excel(writer, index=False, sheet_name='销售表')  # 写入销售表
    df_score.to_excel(writer, index=False, sheet_name='学生成绩表')  # 写入库存表