### 案例1  读取数据 _ 瞧一眼现成JSON原料

In [11]:
import pandas as pd

尝试读取cell_phones_survey.json文件

In [12]:
js = pd.read_json('cell_phones_survey.json')
js

,questionType,asin,answerTime,unixTime,question,answerType,answer
0,yes/no,1466736038,"Mar 8, 2014",1394265600,Is there a SIM card in it?,Y,Yes. The Galaxy SIII accommodates a micro SIM ...
1,yes/no,1466736038,"Jan 29, 2015",1422518400,"Is this phone new, with 1 year manufacture war...",?,It is new but I was not able to get it activat...
2,yes/no,1466736038,"Nov 30, 2014",1417334400,can in it be used abroad with a different carr...,Y,Yes
3,open-ended,1466736038,"Nov 3, 2014",1415001600,What is the warranty on this?,NaN,No warranty
4,yes/no,1466736038,"Oct 2, 2014",1412233200,Does this phone use the regular Sim card (the ...,?,it takes mini sim
5,open-ended,1466736038,"Sep 11, 2014",1410418800,how much time you need to send me this product...,NaN,If you choose expedited shipping you will have...
6,yes/no,1621911888,"Dec 13, 2013",1386921600,Is it unlocked?,Y,yes

### 案例2  读取及保存数据 _ 瞧一眼现成CSV原料

尝试读取fifa_players.csv文件

In [13]:
file_csv = pd.read_csv('fifa_players.csv')
file_csv

C:\Users\赵俊熙\AppData\Local\Temp\ipykernel_32428\1290170686.py:1: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  file_csv = pd.read_csv('fifa_players.csv')

,player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url
0,158023,/player/158023/lionel-messi/150002,15,2,2014-09-18,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,...,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png
1,20801,/player/20801/c-ronaldo-dos-santos-aveiro/150002,15,2,2014-09-18,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,...,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png
2,9014,/player/9014/arjen-robben/150002,15,2,2014-09-18,A. Robben,Arjen Robben,"RM, LM, RW",90,90,...,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png
3,41236,/player/41236/zlatan-ibrahimovic/150002,15,2,2014-09-18,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,...,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png
4,167495,/player/167495/manuel-neuer/150002,15,2,2014-09-18,M. Neuer,Manuel Peter Neuer,GK,90,90,...,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,269011,/player/269011/ziye-zhao/230002,23,2,2022-09-26,Zhao Ziye,赵梓业,RW,46,61,...,32+2,32+2,37+2,36+2,31+2,31+2,31+2,36+2,14+2,https://cdn.sofifa.net/players/269/011/23_120.png
161579,269019,/player/269019/junjie-wu/230002,23,2,2022-09-26,Wu Junjie,吴俊杰,LB,46,58,...,41+2,41+2,43+2,44+2,48+2,48+2,48+2,44+2,15+2,https://cdn.sofifa.net/players/269/019/23_120.png
161580,271093,/player/271093/kailin-barlow/230002,23,2,2022-09-26,K. Barlow,Kailin Barlow,CDM,46,58,...,45+2,45+2,47+2,47+2,46+2,46+2,46+2,47+2,14+2,https://cdn.sofifa.net/players/271/093/23_120.png
161581,271555,/player/271555/gideon-tetteh/230002,23,2,2022-09-26,G. Tetteh,Gideon Tetteh,"RW, LW",46,70,...,30+2,30+2,34+2,32+2,28+2,28+2,28+2,32+2,15+2,https://cdn.sofifa.net/players/271/555/23_120.png
161582,271608,/player/271608/aqeel-al-dhafeeri/230002,23,2,2022-09-26,A. Al Dhafeeri,Aqeel Al Dhafeeri,CB,46,63,...,40+2,40+2,39+2,41+2,46+2,46+2,46+2,41+2,13+2,https://cdn.sofifa.net/players/271/608/23_120.png

查看文件的基本信息

In [14]:
file_csv2 = file_csv.head(10)

查看文件中数据的分布情况

In [15]:
file_csv.shape[1]

110

In [16]:
file_csv.shape[0]

161583

将读取到的数据保存至abc.csv文件中,并用空格间隔数据

In [17]:
file_csv2.to_csv('abc.csv',sep=' ')

### 案例3 书56页课堂实训2：

（1）导入“城镇单位就业人员年平均工资.xlsx”文件“按登记注册类型”工作表中的数据。

In [71]:
file_excel = pd.read_excel(r"D:\WeChat\WeChat Files\wxid_6bhgkb19bbfn22\FileStorage\File\2025-03\城镇单位就业人员年平均工资.xlsx",sheet_name='按登记注册类型',index_col=0)
file_excel

,2020年,2019年,2018年,2017年,2016年,2015年,2014年,2013年,2012年,2011年,2010年,2009年,2008年,2007年,2006年,2005年,2004年,2003年,2002年,2001年
国有单位,108132.0,98899.0,89474.0,81114.0,72538.0,65296.0,57296.0,52657.0,48357.0,43483.0,38359.0,34130.0,30287.0,26100.0,21706.0,18978.0,16445.0,14358.0,12701.0,11045.0
城镇集体单位,68590.0,62612.0,60664.0,55243.0,50527.0,46607.0,42742.0,38905.0,33784.0,28791.0,24010.0,20607.0,18103.0,15444.0,12866.0,11176.0,9723.0,8627.0,7636.0,6851.0
股份合作单位,83655.0,81058.0,77751.0,71871.0,65962.0,60369.0,54806.0,48657.0,43433.0,36740.0,30271.0,25020.0,21497.0,17613.0,15190.0,13808.0,11710.0,10558.0,9498.0,8446.0
联营单位,88584.0,75220.0,72107.0,61467.0,53455.0,50733.0,49078.0,43973.0,42083.0,36142.0,33939.0,29474.0,27576.0,23746.0,19883.0,17476.0,15218.0,13556.0,12438.0,11882.0
有限责任公司,84439.0,79515.0,72114.0,63895.0,58490.0,54481.0,50942.0,46718.0,41860.0,37611.0,32799.0,28692.0,26198.0,22343.0,19366.0,17010.0,15103.0,13358.0,11994.0,11024.0
股份有限公司,108583.0,103087.0,93316.0,85028.0,78285.0,72644.0,67421.0,61145.0,56254.0,49978.0,44118.0,38417.0,34026.0,28587.0,24383.0,20272.0,18136.0,15738.0,13815.0,12333.0
其他单位,71772.0,71329.0,61666.0,54417.0,49759.0,46945.0,42224.0,38306.0,34694.0,29961.0,25253.0,21633.0,19591.0,16280.0,13262.0,11230.0,10211.0,10670.0,10444.0,11888.0
港、澳、台商投资单位,100155.0,91304.0,82027.0,73016.0,67506.0,62017.0,55935.0,49961.0,44103.0,38341.0,31983.0,28090.0,26083.0,22593.0,19678.0,17833.0,16237.0,15155.0,14197.0,12959.0
数据来源：国家统计局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

（2）删除“数据来源：国家统计局”行的数据。

In [ ]:
file_excel.drop(index='数据来源：国家统计局',inplace=True)
# file_excel

（3）选取2014-2019年的数据

In [90]:
data_selected = file_excel.loc[:,'2019年':'2014年']
data_selected

               2019年    2018年    2017年    2016年    2015年    2014年
国有单位         98899.0  89474.0  81114.0  72538.0  65296.0  57296.0
城镇集体单位       62612.0  60664.0  55243.0  50527.0  46607.0  42742.0
股份合作单位       81058.0  77751.0  71871.0  65962.0  60369.0  54806.0
联营单位         75220.0  72107.0  61467.0  53455.0  50733.0  49078.0
有限责任公司       79515.0  72114.0  63895.0  58490.0  54481.0  50942.0
股份有限公司      103087.0  93316.0  85028.0  78285.0  72644.0  67421.0
其他单位         71329.0  61666.0  54417.0  49759.0  46945.0  42224.0
港、澳、台商投资单位   91304.0  82027.0  73016.0  67506.0  62017.0  55935.0

（4）选取2014-2019年的国有单位和联营单位的平均工资并输出

In [91]:
file_excel.loc[['国有单位','联营单位'],'2019年':'2014年']

        2019年    2018年    2017年    2016年    2015年    2014年
国有单位  98899.0  89474.0  81114.0  72538.0  65296.0  57296.0
联营单位  75220.0  72107.0  61467.0  53455.0  50733.0  49078.0

（5）在最后增加一行数据，数据为2001-2020年外商投资单位就业人员的年平均工资列表[112089,106604,99367,90064,82902,76302,69826,63171,55888,48869,41739,37101,34250,29594,26552,23625,22250,21016,19409,17553]

In [97]:
list = [112089,106604,99367,90064,82902,76302,69826,63171,55888,48869,41739,37101,34250,29594,26552,23625,22250,21016,19409,17553]
file_excel.loc['外商投资单位'] =list[::-1]
file_excel

,2020年,2019年,2018年,2017年,2016年,2015年,2014年,2013年,2012年,2011年,2010年,2009年,2008年,2007年,2006年,2005年,2004年,2003年,2002年,2001年
国有单位,108132.0,98899.0,89474.0,81114.0,72538.0,65296.0,57296.0,52657.0,48357.0,43483.0,38359.0,34130.0,30287.0,26100.0,21706.0,18978.0,16445.0,14358.0,12701.0,11045.0
城镇集体单位,68590.0,62612.0,60664.0,55243.0,50527.0,46607.0,42742.0,38905.0,33784.0,28791.0,24010.0,20607.0,18103.0,15444.0,12866.0,11176.0,9723.0,8627.0,7636.0,6851.0
股份合作单位,83655.0,81058.0,77751.0,71871.0,65962.0,60369.0,54806.0,48657.0,43433.0,36740.0,30271.0,25020.0,21497.0,17613.0,15190.0,13808.0,11710.0,10558.0,9498.0,8446.0
联营单位,88584.0,75220.0,72107.0,61467.0,53455.0,50733.0,49078.0,43973.0,42083.0,36142.0,33939.0,29474.0,27576.0,23746.0,19883.0,17476.0,15218.0,13556.0,12438.0,11882.0
有限责任公司,84439.0,79515.0,72114.0,63895.0,58490.0,54481.0,50942.0,46718.0,41860.0,37611.0,32799.0,28692.0,26198.0,22343.0,19366.0,17010.0,15103.0,13358.0,11994.0,11024.0
股份有限公司,108583.0,103087.0,93316.0,85028.0,78285.0,72644.0,67421.0,61145.0,56254.0,49978.0,44118.0,38417.0,34026.0,28587.0,24383.0,20272.0,18136.0,15738.0,13815.0,12333.0
其他单位,71772.0,71329.0,61666.0,54417.0,49759.0,46945.0,42224.0,38306.0,34694.0,29961.0,25253.0,21633.0,19591.0,16280.0,13262.0,11230.0,10211.0,10670.0,10444.0,11888.0
港、澳、台商投资单位,100155.0,91304.0,82027.0,73016.0,67506.0,62017.0,55935.0,49961.0,44103.0,38341.0,31983.0,28090.0,26083.0,22593.0,19678.0,17833.0,16237.0,15155.0,14197.0,12959.0
外商投资单位,17553.0,19409.0,21016.0,22250.0,23625.0,26552.0,29594.0,34250.0,37101.0,41739.0,48869.0,55888.0,63171.0,69826.0,76302.0,82902.0,90064.0,99367.0,106604.0,112089.0

（6）将修改后的数据保存到“按登记注册类型城镇单位就业人员年平均工资.xlsx”文件中。

In [98]:
file_excel.to_excel('按登记注册类型城镇单位就业人员年平均工资.xlsx')