In [30]:
import pandas as pd

exam_time_sheet = pd.read_excel('2024--2025学年下学期期末考试日程表.xlsx',header=1)
exam_time_sheet

,序号,科目,年级,专业,班级,人数,层次,日期,时间,地点,形式,类型,备注
0,1,大数据技术原理与应用,2022,智能医学工程,1.0,17,本科,2025--05--26,13:30--15:00,语音室10（X楼3楼6区305-306）,机考,正考,NaN
1,2,大数据技术原理与应用,2022,智能医学工程,2.0,12,本科,2025--05--26,13:30--15:00,语音室10（X楼3楼6区305-306）,机考,正考,NaN
2,3,Java Web应用开发,2022,医学信息工程,1.0,16,本科,2025--05--27,09:30--11:00,智能信息技术实验室1（X4308）,机考,正考,NaN
3,4,Java Web应用开发,2022,医学信息工程,2.0,17,本科,2025--05--27,09:30--11:00,智能信息技术实验室1（X4308）,机考,正考,NaN
4,5,数字信号处理,2021,医学信息工程,2.0,1,本科,2025--05--28,09:30--11:00,语音室10（X楼3楼6区305-306）,机考,重修,张仁则
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5092,5093,基础医学综合,2023,眼视光医学,1.0,30,本科,2025--07--11,13:00--15:30,语音室1(基础楼三楼）,机考,正考,NaN
5093,5094,基础医学综合,2023,眼视光医学,2.0,27,本科,2025--07--11,13:00--15:30,语音室1(基础楼三楼）,机考,正考,NaN
5094,5095,基础医学综合,2023,眼视光医学,3.0,29,本科,2025--07--11,13:00--15:30,语音室2(基础楼三楼）,机考,正考,NaN
5095,5096,基础医学综合,2023,眼视光医学,4.0,29,本科,2025--07--11,13:00--15:30,语音室2(基础楼三楼）,机考,正考,NaN
5096,5097,基础医学综合,2023,眼视光医学,5.0,29,本科,2025--07--11,13:00--15:30,语音室2(基础楼三楼）,机考,正考,NaN

In [31]:
exam_time_sheet.columns

Index(['序号', '科目', '年级', '专业', '班级', '人数', '层次', '日期', '时间', '地点', '形式', '类型',
       '备注'],
      dtype='object')

In [36]:
filtered_data = exam_time_sheet[
    (exam_time_sheet['年级'] == 2023) & 
    (exam_time_sheet['专业'] == '智能医学工程') &
    (exam_time_sheet['类型'] == '正考')
]
filtered_data

,序号,科目,年级,专业,班级,人数,层次,日期,时间,地点,形式,类型,备注
340,341,数据分析,2023,智能医学工程,1.0,28,本科,2025--06--16,09:30--11:00,X楼2楼3区205,笔试,正考,NaN
1078,1079,概率论与数理统计,2023,智能医学工程,1.0,28,本科,2025--06--30,14:30--16:00,X楼3楼3区307-308,笔试,正考,NaN
2448,2449,毛泽东思想和中国特色社会主义理论体系概论,2023,智能医学工程,1.0,28,本科,2025--07--07,12:00--13:30,X楼2楼3区211,笔试,正考,NaN
2960,2961,大学英语4,2023,智能医学工程,1.0,28,本科,2025--07--07,14:20--15:30,X楼2楼3区205,笔试,正考,NaN

In [37]:
with pd.ExcelWriter('2024--2025学年下学期期末考试日程表.xlsx',engine='openpyxl') as writer:
    filtered_data.to_excel(writer,sheet_name='right',index=False)